### ISSUE TITLE
修改教程，使用新版格式编写 action

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-website#149]
https://www.steedos.com/developer/guide_button

参考以下格式修改教程
https://www.steedos.com/developer/object_action

**Comment by yinlianghui** [comment]
- 源码已调整添加了`accounts.action.js`，按钮能生效。
- 其他的合并到新任务【教程升级到 1.21，同时因为 accounts 已经是标准业务对象，需要调整教程内容 #150】中了。
