### ISSUE TITLE
pdf/office文档在线预览服务进文档

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-website#209]
[配置在线预览服务，启用在线查看office文档 #513](https://github.com/steedos/steedos-platform/issues/513)
[在线预览PDF文件、Office文件 #304](https://github.com/steedos/steedos-platform/issues/304)

配置文档需要增加相关属性说明，https://www.steedos.com/help/deploy/steedos-config

**Comment by chenzhipei** [comment]
pdf: public.webservices.pdfOnline.url="http://oss.steedos.com/apps/pdfviewer-es5/web/viewer.html?rangeChunkSize=1024&file="
office: public.webservices.officeOnline.url="https://view.officeapps.live.com/op/view.aspx?src="

**Comment by ylpmikasa** [comment]
https://www.steedos.com/help/deploy/steedos-config/#%E6%96%87%E4%BB%B6%E5%AD%98%E5%82%A8
