### ISSUE TITLE
默认排序规则文档错误，示例代码里既不是创建时间也不是倒序

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-website#234]
需要确认下目前规则再改正下文档。
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/6219465/121852108-91e12b80-cd21-11eb-89b6-82b5b11b0b81.png">

**Comment by Flyingliao** [comment]
测试结果： 如果未指定是按创建时间倒序排列。 代码描述错误，已修正、发布。
